[toolchain]
channel = "stable-2026-03-05"
components = ["cargo", "clippy", "rust-src", "rustc", "rustfmt"]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
  "armv7-unknown-linux-musleabihf",
  "arm-unknown-linux-musleabihf",  # armv6
  "aarch64-apple-darwin",
  "x86_64-pc-windows-gnu"
]
