name: release

on:
  push:
    tags: ["v*"]

concurrency:
  group: release

permissions:
  contents: read
  packages: write

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e785b8c9ec9fda8072a535786ee5db33429afe4e # v1.12.0

      - name: Check
        run: nix flake check

  release:
    needs: check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        id: checkout
        uses: spotdemo4/better-checkout@eaec73409dbe842ad8446ee818976878b0e9108d # v0.0.2
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Release
        uses: spotdemo4/nix-flake-release@705a37cf5f4a18304b19c853cf9abc575a71a757 # v0.6.0
        with:
          GITHUB_TOKEN: ${{ steps.checkout.outputs.token }}
