name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - id: init
        name: Initialize
        uses: spotdemo4/nix-init@757d5ba1fa0749e877484703bece0e17c7bd5670 # v1.43.0
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          fetch_depth: 0
          shell: release

      - name: Release to GitHub
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ steps.init.outputs.token }}
          REGISTRY: ghcr.io
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES: |-
            packages.x86_64-linux.default.x86_64-linux
            packages.x86_64-linux.default.aarch64-linux
            packages.x86_64-linux.default.armv7l-linux
            packages.x86_64-linux.default.armv6l-linux
            packages.x86_64-linux.default.x86_64-windows
            images.x86_64-linux.default.x86_64-linux
            images.x86_64-linux.default.aarch64-linux
            images.x86_64-linux.default.armv7l-linux

  darwin:
    runs-on: macos-latest
    steps:
      - id: init
        name: Initialize
        uses: spotdemo4/nix-init@757d5ba1fa0749e877484703bece0e17c7bd5670 # v1.43.0
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          fetch_depth: 0
          shell: release

      - name: Release to GitHub
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ steps.init.outputs.token }}
          REGISTRY: ghcr.io
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES: |-
            packages.aarch64-darwin.default.aarch64-darwin
            packages.aarch64-darwin.default.x86_64-darwin
